import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Privacy = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 mt-24 mb-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          
          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-4">Last Updated: December 26, 2024</p>
            
            <p className="mb-6">Thank you for your interest in our website www.playerhub.co (the "Website"), and our mobile application "PlayerHub" (the "App"), which may be available now or in the future, that are owned and operated by Player Hub, Inc., hereafter collectively referred to in this Privacy Policy as "PlayerHub", "us", "our" or "we". Unless otherwise specified, all references to our services (the "Service" or "Services") include the content, services and products available through the PlayerHub Website and App, as well as any software that PlayerHub provides to you that allows you to access the Services though the Website and through our App. The term "user", "you" or "your" refers to the user of our Website, App and our Service, including, without limitation, "Athletes", "Recruiters", "Coaches", "Trainers" and visitors that do not register for an account.</p>

            <p className="mb-6">PlayerHub respects the privacy of your personal information and, as such, we make every effort to ensure your information is protected and remains private. We have provided this Privacy Policy to explain how we collect, use, share and protect information about the users of our Website and our App. We will not use or share your personal information with anyone except as described in this Privacy Policy.</p>

            <p className="mb-6">PlayerHub collects information about you when you use our Website or App to access our Services, software, content, information, applications, recommendations, email notifications, direct messages and other mediums, or portions of such mediums, that PlayerHub provides to you, collectively the Services.</p>

            <p className="mb-6">This Privacy Policy will inform you about the types of personal information we collect, the purposes for which we use the data, the ways in which the data is handled and your rights with regard to your personal information.</p>

            <p className="mb-6">By using, accessing, or interacting with our Website or App, and our Services, you consent to the collection, use, storage, transfer and sharing of personal information that we receive from you through such use, access, and interactions with us as described in this Privacy Policy.</p>

            <p className="mb-6">For purposes of this Privacy Policy, "Your Information" or "Personal Information" means information about you, which may be of a confidential or sensitive nature and may include personally identifiable information ("PII"). PII means individually identifiable information that would allow us to determine the actual identity of a specific living person, while sensitive data may include other information, comments, content and other information that you voluntarily provide.</p>

            <p className="mb-6">We may change this Privacy Policy from time to time. If we decide to change this Privacy Policy, we will inform you by posting the revised Privacy Policy on the Website or sending a notice to your registered email address. If the changes to the Privacy Policy are significant, the email notice we send you may require you to accept the revised Privacy Policy terms. Those changes will go into effect on the "Last updated" date shown at the end of this Privacy Policy. By continuing to use the Website or App and Services, you constructively consent to the revised Privacy Policy. We encourage you to periodically review the Privacy Policy for the latest information on our privacy practices.</p>

            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 my-8">
              <p className="font-medium">BY YOUR USE, AND CONTINUING USE, OF THE WEBSITE OR APP AND OUR SERVICES, YOU AGREE TO THE TERMS OF THIS PRIVACY POLICY AND YOU CONSENT TO THE COLLECTION, TRANSFER, MANIPULATION, STORAGE, DISCLOSURE AND OTHER USES OF YOUR INFORMATION (COLLECTIVELY, "USE OF YOUR INFORMATION") AS DESCRIBED IN THIS PRIVACY POLICY AND OUR TERMS OF USE WHICH MAY BE ACCESSED HERE (INSERT LINK TO TERMS OF USE PAGE HERE). IF YOU DO NOT, OR NO LONGER, AGREE WITH OR CONSENT TO THIS PRIVACY POLICY AND OUR TERMS OF USE YOU MAY NOT ACCESS OR USE OUR SERVICES.</p>
            </div>

            <h2 className="text-xl font-semibold mt-8 mb-4">Information Provided Directly By You</h2>
            <p className="mb-6">We collect information you provide directly to us, such as when you request information about our Services, create or modify your personal account, enroll in an available Subscription Plan or newsletter, make a purchase, request Services, complete a PlayerHub form, survey, questionnaire or application, contact customer support, join or enroll for an event or otherwise communicate with us in any manner. This information may include, but is not limited to, your name, date of birth, e-mail address, business name and physical address. For Athletes this may also include graduation year, height, weight, position and other relevant athletic details.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Information Collected Through Your Use of Our Services</h2>
            <p className="mb-6">We may collect certain information about you automatically when you visit or use our Services, or when you interact with emails, advertisements, or other electronic messages we send to you through the Services. This information may include your IP address, device characteristics (including device identifiers), web browser characteristics, unique identifiers and other data stored in cookies, operating system details, language preference, referring URLs, length of visits, pages viewed, and other information that may be automatically accessible to us from your browser or device.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Information Collected From Other Sources Including Third Party Social Networking Sources</h2>
            <p className="mb-6">We may also receive information from other sources and combine that with information we collect through our Services. For example if you choose to link, create, or log in to your PlayerHub account with a social media and networking service, e.g. Facebook, Instagram, LinkedIn or X (formerly Twitter), or if you engage with a separate application or website that uses our API, or whose API we use, we may receive information about you or your connections from that website or application. This includes, without limitation, profile information, profile picture, gender, user name, user ID associated with your social network or media account, age range, language, country, friends list, your contact names, e-mail addresses, phone numbers, and other identifiers and any other information you permit the social media and networking service to share with third parties. The data we receive is solely dependent upon the privacy settings you have selected with the social media and networking service. You agree that you have read the third party social media or networking service Terms of Service and Privacy Policy, authorize PlayerHub to access certain information about you that is made available through that third party social networking site, and further authorize us to collect, store, retain and use, Your Information in accordance with our Privacy Policy.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Aggregated Data</h2>
            <p className="mb-6">We may collect, use and share “Aggregated Data” such as statistical or demographic data for any purpose. Aggregated Data is de-identified or anonymized and does not constitute Personal Information as this data does not directly or indirectly reveal your identity. If we ever combine Aggregated Data with your Personal Information so that it can directly or indirectly identify you, we treat the combined data as PII which will only be used in accordance with this Privacy Policy.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Cookie Policy, Log Files and Anonymous Identifiers</h2>
            <p className="mb-6">When you visit our Services, we may send one or more Cookies – small data files – to your device to uniquely identify your browser and let us help you log in faster and enhance your navigation through the platforms. “Cookies” are text-only pieces of information that we may transfer to an individual’s device for record keeping purposes. A Cookie may convey anonymous information to us about how you browse the Services so we can provide you with a more personalized experience, but does not collect Personal Information about you. Cookies allow our Service to remember important information that will make your use of the Service more convenient. A Cookie will typically contain the name of the domain from which the Cookie has come, the “lifetime” of the Cookie, and a randomly generated unique number or other value. Certain Cookies may be used on the Sites regardless of whether you are logged in to your account or not.</p>
            <p className="mb-6">Session Cookies are temporary Cookies that remain in the Cookie file of your browser until you leave the Website.</p>
            <p className="mb-6">Persistent Cookies remain in the Cookie file of your browser for much longer (though how long will depend on the lifetime of the specific Cookie).</p>
            <p className="mb-6">When we use session Cookies to track the total number of visitors to our Website, this is done on an anonymous aggregate basis (as Cookies do not in themselves carry any Personal Information).</p>
            <p className="mb-6">We may also employ Cookies so that we remember your device when it is used to return to the Website to help customize your web experience. We may associate Personal Information with a Cookie file in those instances.</p>
            <p className="mb-6">We use Cookies to help us know that you are logged on, provide you with features based on your preferences, understand when you are interacting with our Services, and compile other information regarding use of our Services.</p>
            <p className="mb-6">Third parties with whom we partner to provide certain features on our Website or to display advertising based upon your Web browsing activity (including Affiliates and Sponsors) use Cookies to collect and store information.</p>
            <p className="mb-6">Our Website may use remarketing services, to serve ads on our behalf across the internet on third party websites to previous visitors to our Website. It could mean that we advertise to previous visitors who haven’t completed a task on our Website. This could be in the form of an advertisement on the Google search results page or a website in the Google Display Network. Third-party vendors, including Google, use Cookies to serve ads based on your past visits to our Website. Any data collected will be used in accordance with our own privacy policy, as well as Google's privacy policies. To learn more, or to opt-out of receiving advertisements tailored to your interests by our third parties, visit the Network Advertising Initiative at www.networkadvertising.org/choices.</p>
            <p className="mb-6">We may use third-party services such as Google Analytics to help understand use of the Services. These services typically collect the information sent by your browser as part of a web page request, including Cookies and your IP address. They receive this information and their use of it is governed by their respective privacy policies. You may opt-out of Google Analytics for Display Advertisers including AdWords and opt-out of customized Google Display Network ads by visiting the Google Ads Preferences Manager here https://adssettings.google.com/authenticated?hl=en. To provide website visitors more choice on how their data is collected by Google Analytics, Google has developed an Opt-out Browser add-on, which is available by visiting Google Analytics Opt-out Browser Add-on here https://tools.google.com/dlpage/gaoptout. For additional information on how Google uses data when you use Google partners’ sites or apps, go here: https://policies.google.com/technologies/partner-sites.</p>
            <p className="mb-6">You can control the use of Cookies at the individual browser level. Use the options in your web browser if you do not wish to receive a Cookie or if you wish to set your browser to notify you when you receive a Cookie. You can easily delete and manage any Cookies that have been installed in the Cookie folder of your browser by following the instructions provided by your particular browser manufacturer. Consult the documentation that your particular browser manufacturer provides. You may also consult your mobile device documentation for information on how to disable Cookies on your mobile device. If you reject Cookies, you may still use our Website, but your ability to use some features or areas of our Service may be limited.</p>
            <p className="mb-6">We cannot control the use of Cookies by third parties (or the resulting information), and use of third party Cookies is not covered by this policy.</p>
            <p className="mb-6">We automatically collect information about how you interact with our Services, preferences expressed, and settings chosen and store it in Log Files. This information may include internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and/or clickstream data. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, to improve marketing, analytics, or Website functionality, and to document your consent to receiving products, services or communications from us or our partners. If we link such information with personally identifiable information in a manner that identifies a particular individual, then we will treat all such information as PII for purposes of this Privacy Policy.</p>
            <p className="mb-6">When you use our Services, we may employ Web Beacons (also known as clear GIFs or tracking pixels) to anonymously track online usage patterns. No Personally Identifiable Information from your account is collected using these Web Beacons.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Device Information</h2>
            <p className="mb-6">When you use our Services through your mobile phone or other digital devices, we may collect information regarding and related to your device, such as hardware models and IDs, device type, operating system version, the request type, the content of your request and basic usage information about your use of our Services, such as date and time. In addition, we may collect information regarding application-level events and associate that with your account to provide customer service. We may also collect and store information locally on your device using mechanisms such as browser web storage and application data caches.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Call and SMS Data</h2>
            <p className="mb-6">In connection with providing Service, we may receive call data, including the date and time of the call or SMS message, the parties phone numbers, and the content of the SMS message. You consent to the receipt, collection and storage of this information.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Children's Privacy</h2>
            <p className="mb-6">We do not knowingly collect personally identifiable information (PII) from persons under the age of 13 in the United States ("U.S."), or under the age of 16 in the European Union ("EU"), the "Protected Age" unless we receive consent to do so from a parent or a legal guardian. If you are under the Protected Age, please do not provide us with information of any kind whatsoever. If you have reason to believe that we may have accidentally received information from a child under the Protected Age, without receiving the consent of a parent or legal guardian, please contact us immediately. If we become aware that we have inadvertently received Personal Information from a person under the Protected Age, we will delete such information from our records.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Protective Measures We Use</h2>
            <p className="mb-6">We protect Your Information using commercially reasonable technical and administrative security measures to reduce the risks of loss, misuse, unauthorized access, disclosure and alteration. Some of the safeguards we use are firewalls and data encryption, physical access controls to our data centers, and information access authorization controls. Although we take measures to secure Your Information, we do not promise, and you should not expect, that your Personal Information, or searches, or other information will always remain secure. We cannot guarantee the security of our information storage, nor can we guarantee that the information you supply will not be intercepted while being transmitted to and from us over the Internet including, without limitation, email and text transmissions. In the event that any information under our control is compromised as a result of a breach of security, we will take reasonable steps to investigate the situation and where appropriate, notify those individuals whose information may have been compromised and take other steps, in accordance with any applicable laws and regulations.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Payment Information</h2>
            <p className="mb-6">PlayerHub may accept payments on our Website or in our App and will use a secure third party payment processing gateway to collect, store and process payment information. That information will be provided directly to the third party payment processors whose use of your Personal Information is governed by their Privacy Policy. PlayerHub will not store this information on our Website, in our App or in our servers.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">How We Use Information We Collect</h2>
            <p className="mb-6">We will not rent, sell, lease or trade Your Information to anyone unless you grant us explicit permission for this information to be shared in that manner. Our primary purpose in collecting, holding, using and disclosing your Information is for our legitimate business purposes and to provide you with a safe, smooth, efficient, and customized experience. We will use this information in order to:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Operate and provide our Services;</li>
              <li>Improve our internal operations, systems, products, and Services;</li>
              <li>Provide users with customer support including, sending you related information, including confirmations, technical notices, updates, security alerts, and administrative messages;</li>
              <li>Understand you and your preferences to enhance your experience and enjoyment using our Services;</li>
              <li>Analyze, improve and manage our Services and operations;</li>
              <li>Contact you for administrative, account maintenance purposes;</li>
              <li>Resolve problems and disputes, and engage in other legal and security matters;</li>
              <li>Protect, investigate, and deter against fraudulent, unauthorized, or illegal activity;</li>
              <li>Enforce our Terms of Use and any terms and conditions of any agreements for our Services;</li>
              <li>Send you communications we think will be of interest to you, including information about our services, products, promotions, events and news about PlayerHub;</li>
              <li>Verify your identity and prevent impersonation, spam or other unauthorized or illegal activity including, without limitation, infringement of intellectual property rights of third parties.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">How We Share Information We Collect</h2>
            <p className="mb-6">We share the information we collect about you as described in this Privacy Policy, or as described at the time of collection or sharing, as follows:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>With third party Service Providers to enable them to provide the Services you request. Access to your Personal Information by these Service Providers is limited to the information reasonably necessary in order for them to perform their limited function for us. We also require that these Service Providers (a) protect the privacy of your Personal Information consistent with this Privacy Policy, and (b) not use or disclose your Personal Information for any purpose other than providing us with products or services for which we contracted;</li>
              <li>With third parties with whom you choose to let us share information, for example other websites or apps that integrate with our API or Services, or those with an API or Service with which we integrate;</li>
              <li>With PlayerHub subsidiaries and affiliated entities that provide services or conduct data processing on our behalf, or for data verification, data centralization and/or logistics purposes. Any information relating to you that we provide to our subsidiaries and affiliated entities will be treated by those parties in accordance with the terms of this Privacy Policy;</li>
              <li>With Service Providers that may now or in the future provide payment processing services on our behalf. Access to your Personal Information by these Service Providers is limited to the information reasonably necessary in order for them to perform their limited function for us. We also require that these Service Providers (a) protect the privacy of your Personal Information consistent with this Privacy Policy, and (b) not use or disclose your Personal Information for any purpose other than providing us with products or services for which we contracted;</li>
              <li>With vendors, consultants, marketing partners, and other Service Providers who need access to such information to carry out work on our behalf. Access to your Personal Information by these Service Providers is limited to the information reasonably necessary in order for them to perform their limited function for us. We also require that these Service Providers (a) protect the privacy of your Personal Information consistent with this Privacy Policy, and (b) not use or disclose your Personal Information for any purpose other than providing us with products or services for which we contracted;</li>
              <li>In response to a request for information by a competent authority if we believe disclosure is in accordance with, or is otherwise required by, any applicable law, regulation, court or legal process;</li>
              <li>With law enforcement officials, government authorities, or other third parties if we believe your actions are inconsistent with our Terms of Use or policies, or to protect the rights, property, or safety of PlayerHub or others;</li>
              <li>In connection with, or during negotiations of, any merger, sale of company assets, consolidation or restructuring, financing, or acquisition of all or a portion of our business by or into another company. We require that these parties (a) protect the privacy of your Personal Information consistent with this Privacy Policy, and (b) not use or disclose your Personal Information for any purpose;</li>
              <li>If we otherwise notify you and you consent to the sharing; and,</li>
              <li>In an aggregated and/or de-identified form which cannot reasonably be used to identify you. We only use such data in the aggregate form and our analytical services do not record any Personal Information.</li>
            </ul>
            <p className="mb-6">We may disclose Your Information as follows:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>To any person who, in our reasonable judgment, is authorized to receive Your Information as your agent, including as a result of your business dealings with that person (for example, your attorney);</li>
              <li>As required by law or ordered by a court, regulatory, or administrative agency;</li>
              <li>As we deem necessary, in our sole discretion, if we believe that you are violating any applicable law, rule or regulation, or are otherwise interfering with another's rights or property, including, without limitation, our rights or property;</li>
              <li>To enforce our Terms of Use, this Privacy Policy, and any other applicable agreements and policies.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Sharing Information With Law Enforcement</h2>
            <p className="mb-6">PlayerHub is committed to cooperating with law enforcement while respecting each individual’s right to privacy. If PlayerHub receives a request for user account information from a government agency investigating criminal activity, we will review the request to be certain that it satisfies all legal requirements before releasing information to the requesting agency.</p>
            <p className="mb-6">Furthermore, under 18 U.S.C. §§ 2702(b)(8) and 2702(c)(4) (Voluntary Disclosure Of Customer Communications or Records), PlayerHub may disclose user account information to law enforcement, without a subpoena, court order, or search warrant, in response to a valid emergency when we believe that doing so is necessary to prevent death or serious physical harm to someone. PlayerHub will not release more information than it prudently believes is necessary to prevent harm in an emergency situation.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Social Network or Media Sharing</h2>
            <p className="mb-6">Our Services may now, or in the future, integrate with other services providing social network sharing features, and other related tools, that allow you to share actions you take on our Services with other applications, websites, or media, and vice versa. Your use of such features enables the sharing of information with your friends or the public, depending on the settings you establish with the social network sharing service. Please refer to the privacy policies of those social network sharing services for more information about how they handle the data you provide to, or share through them.</p>
            <p className="mb-6">Any information or content that you voluntarily disclose for posting publicly to a social network sharing service becomes available to the public, as controlled by any applicable privacy settings that you set with the social network sharing service. Once you have shared User Content or made it public, that User Content may be re-shared by others. If you remove information that you posted to the social network sharing service, copies may still remain viewable in cached and archived pages, or if other users or third parties, using the social network sharing service, have re-shared, copied or saved that User Content.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">User Content and Public Sharing</h2>
            <p className="mb-6">If we permit you to share User Content as defined in our Terms of Use or to post a comment or message that contains personally identifiable information to a page, or area of our Services that is accessible to the public, or accessible to other users of our Service, third parties may use that information, or share it with other parties. As a result, you may receive unsolicited messages from other parties. Such User Content, comments or messages are not subject to this Privacy Policy and you share this information at your own risk.</p>
            <p className="mb-6">You will need to contact PlayerHub in the event that you wish to have this personally identifiable information removed from our Service. Please note that responding to your request may not ensure complete or comprehensive removal from the internet if the content or information has been reposted by another party. To request removal of content or information, please contact us at help@playerhub.co.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Analytic Services Provided By Others</h2>
            <p className="mb-6">We may allow others to provide audience measurement and analytics services for us, to serve advertisements on our behalf across the Internet, and to track and report on the performance of those advertisements. These entities may use Cookies, Web Beacons, software development kits (SDKs), and other technologies to identify your device when you visit our Website and use our Services, as well as when you visit other online sites and services.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Links to Third-Party Websites, Affiliates and Advertisers</h2>
            <p className="mb-6">Our Services, as well as the email messages sent with respect to our Services, may contain links or access to websites operated by third parties that are beyond our control. These third parties may include paid Advertisers or Affiliates that may provide us with compensation when you click on their links. Access or links to third parties from our Services are not an endorsement by us of such third parties, or their websites, applications, merchandise, products, services, or practices. We are not responsible for the privacy policy, terms and conditions, practices or the content of such third parties. These third-parties may send their own Cookies to you and independently collect data.</p>
            <p className="mb-6">If you visit or access a third-party Website, application or other property that is linked or accessed from our Services, we encourage you to read any privacy policies and terms and conditions of that third party before providing any personally identifiable information. If you have a question about the terms and conditions, privacy policy, practices or contents of a third party, please contact the third party directly.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Do Not Track Settings</h2>
            <p className="mb-6">Some web browsers may give you the ability to enable a "do not track" feature that sends signals to the websites you visit, indicating that you do not want your online activities tracked. This is different than blocking or deleting Cookies, as browsers with a "do not track" feature enabled may still accept Cookies. There currently is no accepted standard for how to respond to this signal, and we do not take any action in response to this signal.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">International Privacy Practices; Users Outside of the United States</h2>
            <p className="mb-6">In order to provide our products and services to you, we may send and store your Personal Information outside of the country where you reside or are located, including to the United States. Accordingly, if you reside or are located outside of the United States, your Personal Information may be transferred outside of the country where you reside or are located, including countries that may not, or do not, provide the same level of protection for your Personal Information. We are committed to protecting the privacy and confidentiality of Personal Information when it is transferred. If you reside or are located within the European Union ("EU") or European Economic Area ("EEA") and such transfers occur, we take appropriate steps to provide the same level of protection for the processing carried out in any such countries as you would have within the EU and EEA to the extent feasible under applicable law. By acknowledging that you have read and agree to this Privacy Policy at the time of registering for an account, users who reside, or are located, in countries outside of the United States consent to the transfer to, and processing of, Personal Information on servers located outside of the country where they reside, and assume the risk that the protection of such information may be different, and may be less protective, than those required under the laws of their residence or location.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Account Information</h2>
            <p className="mb-6">You may cancel your account or correct your account information at any time by logging into your online account setting section and clicking cancel subscription in the Billings section, or emailing us at help@playerhub.co and following the directions we provide. Please note that in some cases we may retain certain information about you as required by law, or for legitimate business purposes to the extent permitted by law.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Promotional Information Opt Out</h2>
            <p className="mb-6">You may opt out of receiving promotional messages from us at any time by following the instructions in those messages sent to you or by contacting us at any time using the Contact Us information at the end of this Privacy Policy. In doing so, you elect not to receive correspondence from us or have Your Information shared with other entities for their marketing purposes. If you opt out, we may still send you non-promotional communications, such as those about your account, about Services you have requested, or our ongoing business relations.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">The Legal Basis and Reasons For Collection and Processing Your Personal Information</h2>
            <p className="mb-6">The legal basis upon which we rely for the collection and processing of your Personal Information are the following:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>When registering to use our Services, you have given us explicit consent allowing PlayerHub to provide you with our Services and generally to process Your Information in accordance with this Privacy Policy; and to the transfer of your Personal Information to other jurisdictions including, without limitation, the United States;</li>
              <li>It is necessary for entering into, or performing, the obligations of a contract between you and PlayerHub, including, without limitation, the Terms of Use agreement which may be accessed by you here (insert link to the Terms of Use page here) and any available paid Subscription Plan for our Services that you agree to;</li>
              <li>It is necessary registering you as a user, managing your account and profile, and authenticating you when you log in.</li>
              <li>It is necessary for our legitimate interests in the proper administration of our website and business; analyzing the use of the website and our Services; assuring the security of our website and Services; maintaining back-ups of our databases; and communicating with you;</li>
              <li>To resolve technical issues you encounter, to respond to your requests for assistance, comments and questions, to analyze crash information, to repair and improve the Services and provide other customer support.</li>
              <li>To send communications via email and within the Services, including, for example, responding to your comments, questions and requests, providing customer support, and sending you technical notices, product updates, security alerts, and administrative, billing and account management related messages.</li>
              <li>To send promotional communications that you have consented to receive or have expressed a legitimate interest in receiving.</li>
              <li>It is necessary for our legitimate interests in the protection and assertion of our legal rights, and the legal rights of others, including you;</li>
              <li>It is necessary for our compliance with certain legal provisions which may require us to process your Personal Information. By way of example, and without limitation, we may be required by law to disclose your Personal Information to law enforcement or a regulatory agency.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">General Data Protection Regulation (GDPR); Your Access and Rights to Your Personal Information</h2>
            <p className="mb-6">You have certain rights in relation to Personal Information we hold about you. You can exercise any of the following rights by contacting us using any of the methods in the Contact section below. We may need to request specific information from you to help us confirm your identity and ensure your right to access your Personal Data (or to exercise any of your other rights). This is a security measure to ensure that Personal Data is not disclosed to any person who has no right to receive it. We try to respond to all legitimate requests within one month. Occasionally it may take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated.</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Right to Access Your Personal Data. You have the right to access information held about you for the purpose of viewing and in certain cases updating or deleting such information. Furthermore, if you prefer that we do not share certain information as described in this Privacy Policy, you can direct us not to share that information. We will comply with an individual’s requests regarding access, correction, sharing and/or deletion of the personal data we store in accordance with applicable law. To make changes to your account affecting your personal information contact us at the email address in our Contact section below. For any deletion, non-sharing or update request, we will make the changes as soon as practicable; however this information may stay in our backup files. If we cannot make the changes you want, we will let you know and explain why.</li>
              <li>Right of Correction or Completion of Your Personal Data. If personal information we hold about you is not accurate, out of date or incomplete, you have a right to have the data corrected or completed. To make corrections to your account please contact us at the email address in our Contact section below.</li>
              <li>Right of Erasure or Deletion of Your Personal Data. In certain circumstances, you have the right to request that personal information we hold about you is deleted. If we cannot delete the information you want, we will let you know and explain why. To request deletion of information please contact us at the email address in our Contact section below.</li>
              <li>Right to Object to or Restrict Processing of Your Personal Data. In certain circumstances, you have the right to object to our processing of your personal information. For example, you have the right to object to use of your personal information for direct marketing purposes. Similarly, you have the right to object to use of your personal information if we are processing your information on the basis of our legitimate interests and there are no compelling legitimate grounds for our processing which supersede your rights and interests. You may also have the right to restrict our use of your personal information, such as in circumstances where you have challenged the accuracy of the information and during the period where we are verifying its accuracy. To object to or restrict processing please contact us at the email address in our Contact section below.</li>
              <li>Right to Data Portability or Transfer of Your Personal Data. You have the right to be provided with a copy of the information we maintain about you in a structured, machine-readable and commonly used format. To receive a copy of the information we maintain about you please contact us at the email address in our Contact section below.</li>
              <li>Right to Withdrawal of Consent. If you have given your consent to us to process and share your Personal Information after we have requested it, you have the right to withdraw your consent at any time. To withdraw your consent please contact us at the email address in our Contact section below.</li>
              <li>Right to Complain. You have the right to file a complaint regarding our data protection practices with a supervisory authority. Please see this directory for contact details: https://edpb.europa.eu/about-edpb/board/members_en.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Your California Privacy Rights</h2>
            <p className="mb-6">California Civil Code Section 1798.83 entitles California residents to request information concerning whether a business has disclosed Personal Information to any third parties for their direct marketing purposes. California residents may request and obtain from us once a year, free of charge, information about the Personal Information, if any, we disclosed to third parties for direct marketing purposes within the immediately preceding calendar year. If applicable, this information would include a list of the categories of Personal Information that was shared and the names and addresses of all third parties with which we shared information within the immediately preceding calendar year.</p>
            <p className="mb-6">If you are a California resident and would like to make such a request please contact us using the information in the “Contact Us” section at the end of this document.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Your Nevada Consumer Privacy Rights</h2>
            <p className="mb-6">We do not sell consumers’ covered Personal Information for monetary consideration (as defined in Chapter 603A of the Nevada Revised Statutes). However, if you are a Nevada resident, you have the right to submit a request directing us not to sell your Personal Information. To submit such a request, please contact us using the information in the “Contact Us” section at the end of this document.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Your Canadian Privacy Rights</h2>
            <p className="mb-6">Residents of Canada are permitted to request and obtain from us information regarding the existence, use, and disclosure of their personal information as well as access to that information (subject to certain exceptions pursuant to applicable laws). Without limiting the above, residents of Canada will, upon request:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Be informed of whether we hold personal information about you;</li>
              <li>Be provided with an account of third parties to which we have disclosed personal information about you;</li>
              <li>Be able to challenge the accuracy and completeness of personal information about you and have it amended as appropriate; and</li>
              <li>Be provided with information about our policies and practices with respect to the management of personal information, including: the name or title, and address, of the person who is accountable for our privacy policies and practices; the means of gaining access to personal information; a description of the type of personal information held by us, including a general account of its use; a copy of any brochures or other information, if available that explain our policies, standards, or codes; and what personal information is made available to related organizations.</li>
            </ul>
            <p className="mb-6">To submit such a request, please contact us using the information in the “Contact Us” section at the end of this document.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Your Colorado, Connecticut, Virginia, and Utah Privacy Rights</h2>
            <p className="mb-6">The disclosures in this section apply solely to individual residents of the States of Colorado, Connecticut, Virginia, and Utah. Those rights include:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Right to Access Information. You have the right to access and obtain a copy of your personal data.</li>
              <li>Right to Request Deletion. You have the right to request that we delete personal data provided by or obtained about you.</li>
              <li>Right to Correct. You have the right to correct inaccuracies in your personal data.</li>
              <li>Right to Opt-Out of Targeted Advertising. You may ask us not to use or disclose your information for the purposes of targeting advertising to you based on your personal data obtained from your activity across different businesses, services, websites, etc.</li>
              <li>Right to Opt-Out of Personal Information Sales to third parties.</li>
            </ul>
            <p className="mb-6">To submit such a request, please contact us using the information in the “Contact Us” section at the end of this document.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Our Information Retention Policy</h2>
            <p className="mb-6">Unless you request that we delete certain information, we retain the information we collect for as long as your account is active or as needed to provide you services. Following termination or deactivation of your account, we will retain information for at least 1 year and may retain the information for as long as needed for our business and legal purposes. We will only retain your Personal Information for so long as we reasonably need to unless a longer retention period is required by law (i.e. for regulatory purposes).</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Contact Us</h2>
            <p className="mb-6">If you have any questions or if you would like to contact us about our processing of your Personal Information, including exercising your rights as outlined above, please contact us by using the information below. When you contact us, we will ask you to verify your identity.</p>
            <p className="mb-6">Contact name: Data Protection Officer</p>
            <p className="mb-6">Email: help@playerhub.co</p>

            <p className="mb-6">Player Hub, Inc.</p>
            <p className="mb-6">Last updated: December 26, 2024</p>
          </div>
        </div>
      </main>
      <Footer activePage="privacy" />
    </div>
  );
};

export default Privacy;
