import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Privacy = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 mt-24 mb-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
          
          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-4">Last Updated: December 2024</p>
            
            <p className="mb-6">GO Design Inc. ("we," "us," or "our") operates the PlayerHub.com website and related mobile applications (collectively, the "Services").</p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">Definitions</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Services: The PlayerHub.com website and related mobile applications operated by GO Design Inc. and/or its affiliates.</li>
              <li>Personal Information: Information that identifies, relates to, describes, or could reasonably be linked, directly or indirectly, with a particular individual.</li>
              <li>Usage Data: Data collected automatically, generated by the use of the Services or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
              <li>Cookies: Small pieces of data stored on your device (computer or mobile device) that may include an anonymous unique identifier.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Information Collection and Use</h2>
            <p className="mb-4">We collect various types of information for different purposes to provide and improve our Services.</p>
            
            <h3 className="text-lg font-semibold mt-6 mb-3">Personal Information</h3>
            <p className="mb-4">While using our Services, we may ask you to provide certain personally identifiable information that can be used to contact or identify you, including but not limited to:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Use of Data</h2>
            <p className="mb-4">PlayerHub uses the collected data for various purposes, including but not limited to:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Providing and maintaining our Services</li>
              <li>Notifying you about changes to our Services</li>
              <li>Allowing you to participate in interactive features</li>
              <li>Providing customer support</li>
              <li>Gathering analysis or valuable information to improve our Services</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Contact Us</h2>
            <p className="mb-4">If you have any questions about this Privacy Policy or wish to make a data request, please contact us:</p>
            <p className="mb-4">Email: help@playerhub.com</p>
          </div>
        </div>
      </main>
      <Footer activePage="privacy" />
    </div>
  );
};

export default Privacy;