import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 mt-24 mb-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-8">Terms of Use</h1>
          
          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-4">Last Updated: December 26, 2024</p>
            
            <p className="mb-6">Welcome to our website www.playerhub.co (the "Website"), and our mobile application "PlayerHub" (the "App") which we make available to you now or in the future, and that are owned and operated by Player Hub, Inc., hereafter collectively referred to in these Terms of Use as "PlayerHub", "us", "our" or "we". Unless otherwise specified, all references to our services (the "Service" or "Services") include the content, services and products available through the PlayerHub Website and App, as well as any software that PlayerHub provides to you that allows you to access the Services though the Website and through our App. The term "user", "you" or "your" refers to the user of our Website, App and our Service, including, without limitation, "Athletes", "Recruiters", "Coaches", "Trainers" and visitors that do not register for an account. The following Terms of Use are a legally binding contract between you and PlayerHub regarding your use of the Service.</p>

            <p className="mb-6">Please read the following Terms of Use ("Terms" or "Agreement") carefully before accessing or using any of the Services. Each time you purchase a subscription to our Services, access or use our Services, or purchase something through our Services, you, and if you are acting on behalf of a third party, such third party, agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree to be bound by all of these Terms, you may not access or use our Service. PlayerHub may change this Agreement at any time by posting an updated Terms of Use on this Website. If any amendment to these Terms is unacceptable to you, you shall cease using the Website or the App; otherwise you will be constructively deemed to have accepted the changes.</p>

            <p className="mb-6">In addition, certain areas of the Service may be subject to additional Terms and Conditions that we have made available for your review. By using such areas, or any part thereof, you are expressly indicating that you have read and agree to be bound by the additional Terms and Conditions applicable to such areas. In the event that any of the additional Terms and Conditions governing such area conflict with these Terms, the additional Terms and Condition will control.</p>

            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 my-8">
              <p className="font-bold">PLEASE READ THE BINDING ARBITRATION CLAUSE AND CLASS ACTION WAIVER PROVISIONS IN THE DISPUTE RESOLUTION SECTION OF THESE TERMS. IT AFFECTS HOW DISPUTES ARE RESOLVED. BY ENTERING INTO THIS AGREEMENT, YOU EXPRESSLY ACKNOWLEDGE THAT YOU UNDERSTAND THIS AGREEMENT, INCLUDING THE DISPUTE RESOLUTION, ARBITRATION PROVISIONS AND CLASS ACTION WAIVER AND ACCEPT ALL OF THE TERMS. YOU MAY NOT USE OR ACCESS OUR PLATFORM IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT.</p>
            </div>

            <h2 className="text-xl font-semibold mt-8 mb-4">Eligibility for Our Service</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>By using our Services, you represent and warrant that you have attained the age of majority where you reside (18 years of age in most jurisdictions) and are otherwise capable of entering into binding contracts including this Agreement. Persons who are at least 13 years of age but under the age of majority may only use our Services with parental or legal guardian consent. Accordingly, you agree that you are at least the age of majority or older, or have received legal parental or guardian consent from someone fully able and competent to enter into the terms, conditions, representations and warranties set forth in the Terms.</li>
              <li>We reserve the right to request documented proof of your compliance with these terms of eligibility and if you are under the age of 18 we will send you a Parental/Guardian Consent Form by email that must be completed by a parent or legal guardian and returned before your account will be activated.</li>
              <li>If you are using our Services on behalf of a company or other organization, you represent and warrant that you have authority to act on behalf of that entity and to bind that entity to this Agreement.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Our Service</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>PlayerHub is a SaaS (Software as a Service) Website and mobile application platform that provides youth, scholastic and professional Athletes, Recruiters, Coaches and Trainers the software, programs, tools and abilities to create a sustainable personal profile and digital marketing content (images and video) in order to connect and engage directly with other users of the platform. For Athletes, you will create an "Athlete Profile" and tell your sports story allowing Recruiters, coaches and Trainers a detailed glimpse into your athletic journey and personal narrative, equipping them with the essential tools to quickly begin the evaluation of your talents and skills.</li>
              <li>The software, content, Services and products available in, or through our Website or App are for your personal use only. You may not sell or resell any of the content, Services, software or products we provide to you or which you otherwise receive from us.</li>
              <li>Any modifications and new features added to the Service are also subject to this Agreement.</li>
              <li>PlayerHub reserves the right to modify or discontinue the Service or any feature or functionality thereof at any time without notice to you. All rights, title and interest in and to the Service and its components (including all intellectual property rights) will remain with and belong exclusively to PlayerHub.</li>
              <li>Free Account. PlayerHub offers a free subscription for our Services. Registration for a free account is required. For the free product the user can add/edit every page of their Personal Profile. User can only add up to 8 images and 1 video. If you want to add more you will need to upgrade to the premium plan.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Premium Subscription Plan and Terms</h2>
            <p className="mb-6">PlayerHub offers two (2) paid Subscription Plans for users: a) an annual (12 month) renewable Subscription Plan, and b) a month-to-month renewable Subscription Plan. User can add up to 40 images and 8 videos and can create a custom "Player Card". The features, subscriber rights, terms and prices of this Subscription Plans may change from time to time and the most current descriptions and prices may be found on our Subscription Plan pricing page here (insert link to subscription pricing page or FAQ).</p>

            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>By completing your registration for a Subscription Plan, you authorize PlayerHub or its third party payment processor to charge your payment method on a recurring basis (i.e. annually or monthly) for: (i) the applicable Subscription Plan charges; (ii) any and all applicable taxes; and (iii) any other charges incurred in connection with customer's use of the PlayerHub services. The authorization continues through the subscription term, and any renewal term, until the subscriber cancels the Subscription Plan.</li>
              <li>By purchasing a Subscription Plan, you expressly acknowledge and agree that (i) your subscription has an initial and recurring annual or monthly payment feature, and PlayerHub (or our third party payment processor) is authorized to automatically charge your payment method at the then-current Subscription Plan rate for your subscription period as long as your subscription continues, and (ii) your Subscription Plan is continuous and will be automatically extended for successive subscription periods until you cancel it.</li>
              <li>You may cancel your Subscription Plan at any time, by logging into your account and selecting cancel subscription in the "billing" section of your profile settings or emailing us at help@playerhub.co and following the instructions we provide to you in response to your cancellation request. If you cancel, you will not be entitled to a refund for your last payment and you may use your Subscription Plan until the end of your then-current paid-up subscription term (i.e. last paid month or 12th month of your annual subscription term).</li>
              <li>When your cancel your Subscription Plan or it expires, you will lose access to all features and all data associated with those features.</li>
              <li>PlayerHub may submit periodic charges without further authorization from you, until you provide prior notice that you have terminated this authorization or wish to change your payment method. Such notice will not affect charges submitted before PlayerHub reasonably could act.</li>
              <li>In the event you cancel your Subscription Plan, please note that we may still send you promotional communications about PlayerHub, unless you opt out of receiving those communications by following the unsubscribe instructions provided therein.</li>
              <li>Subscription Plans are non-refundable.</li>
            </ul>

            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 my-8">
              <p className="font-bold">WE RESERVE THE RIGHT TO REVOKE YOUR SUBSCRIPTION AT ANY TIME AS A RESULT OF A VIOLATION OF THESE TERMS AND CONDITIONS OR THE PRIVACY POLICY. SUBSCRIPTION MEMBERSHIP IS VOID WHERE PROHIBITED BY LAW.</p>
            </div>

            <h2 className="text-xl font-semibold mt-8 mb-4">Free Trial Subscription for Trainers</h2>
            <p className="mb-6">PlayerHub offers Trainers a 30 day free trial subscription (a "Free Trial"). A Free Trial provides you access to the Premium Services for 30 days, with details specified when you register for the offer. In order to sign up for a Free Trial, you may need to provide us with your preferred Payment Method. As soon as you submit your payment details, your Free Trial will begin. You will not be charged until the Free Trial period ends. Unless you cancel before the end of the Free Trial, or unless otherwise stated, your access to the Premium Service will automatically continue and you will be billed the applicable fees for that Premium Service using the Payment Method you provided. All incurred charges are final and non-refundable, except at our sole discretion and in accordance with the rules governing each Premium Service. We may send you a reminder when your Free Trial is about to end, but we do not guarantee any such notifications. It is ultimately your responsibility to know when the Free Trial will end if you decide you do not want to become a paying Premium Services user after the Free Trial period. If you decide you do not want to become a paying Premium Services user, you must cancel your subscription before the end of the Free Trial period.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Orders</h2>
            <p className="mb-6">Your subscription order constitutes an offer to purchase annual or month-to-month Subscription Plan and Services available on our platform. We reserve the right at any time to accept or decline any Subscription Plan order. We reserve the right to cancel your order at any time before it has been accepted and we may rescind the acceptance and cancel your order where there has been an obvious error in price or where the Subscription Plan or Services is no longer available.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Prices</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>All Subscription Plan prices are in U.S. dollars unless otherwise indicated.</li>
              <li>All applicable taxes and other charges are additional and your responsibility.</li>
              <li>We reserve the right in our sole discretion to change prices at any time and without notice.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Payment</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>By providing PlayerHub or our third party payment processor with your method of payment information, you authorize us to charge you for Subscription Plan purchases using the secure third party payment processor we make available to you. Our payment gateway partners use secure servers with state-of-the-art encryption and secure sockets layer (SSL) technology for the transfer of credit card information. Additionally, we have security measures in place to protect our customer database and access to this database is restricted internally.</li>
              <li>You must keep all information about your payment method current. If you tell us to stop using your payment method and we no longer receive payment from you, we may cancel your account and subscription. Your notice to us will not affect charges to your account before we reasonably could act on your request.</li>
              <li>You agree that we may charge you, and you will pay to PlayerHub, any fee or penalty that is assessed or charged to us for a "Chargeback" resulting from a failure or refusal of your selected method of payment to make a required payment. This payment shall be refunded to you in the event that your selected method of payment resolves this dispute in your favor.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Accounts and Registration</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>To access some features of the Service users will be required to register for an account. When you register for an account, you will be required to provide us with some information about yourself including, but not limited to, your name, date of birth, e-mail address, business name and physical address. For Athletes this may also include graduation year, height, weight, position and other relevant athletic details.</li>
              <li>If you provide Your Information to us then you agree to provide true, current, complete and accurate information, and not to misrepresent your identity. You also agree to keep Your Information current and to update Your Information if any of Your Information changes.</li>
              <li>Our collection, use and disclosure of Your Information is governed by this Agreement and our Privacy Policy which you may access here (include link to Privacy Policy page here).</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Account Management</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>If you have been issued an account by PlayerHub in connection with your use of the Services, you are responsible for safeguarding your password and any other credentials used to access that account, even if you authorize other parties to access your account. You, and not PlayerHub, are responsible for any activity occurring in your account, whether or not you authorized that activity. If you become aware of any unauthorized access to your account, you should notify PlayerHub immediately.</li>
              <li>As a function of providing our Services PlayerHub may send text messages to your mobile phone or notices to the email address registered with your account. You must keep your email address, mobile phone number and, where applicable, your contact details associated with your account current and accurate. Text message costs may apply and are the user's responsibility, not that of PlayerHub.</li>
              <li>We reserve the right to modify, suspend or terminate the Service, any user account or your access to the Service for any reason, without notice, at any time, and without liability to you.</li>
              <li>You can cancel your account at anytime. Upon termination or cancellation, all licenses and other rights granted to you in these Terms will immediately cease. When your cancel your Subscription Plan or it expires, you will lose access to all features and all data associated with those features.</li>
              <li>We reserve the right to refuse to issue an account to anyone or permit access to the Service to anyone for any reason at any time.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">In Website or App Purchases</h2>
            <p className="mb-6">PlayerHub may now, or in the future, provide you with the ability to make purchases of products and services through an In Website or In App Purchase option using a secure third party payment processing service. If you choose to make an In Website or In App Purchase, you will be prompted to confirm your purchase with the applicable payment processor, and provide them with your preferred method of payment, which will then be charged at the prices displayed to you at the time of purchase, along with any sales tax or other charges. You authorize PlayerHub to charge the payment method you specify at the time of purchase. PlayerHub does not receive or store your method of payment information. If you have any questions regarding your method of payment information, you will need to contact the secure third party payment processing service. Please contact us at help@playerhub.co for instructions on how to contact the payment service.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Your License, Access and Use of our Services</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Subject to your continued compliance with this Agreement, PlayerHub grants you, a limited, non-exclusive, revocable, non-sub-licensable, worldwide, license to access and use the PlayerHub Website, App and Services solely for your personal use. Any other use is expressly prohibited. This license is revocable at any time without notice and with or without cause.</li>
              <li>Your right to access and use our Services is personal to you, or your business entity, and is not transferable by you to any other person or entity. Access to our Services may not be available in all locations. You are only entitled to access and use our Services for lawful purposes and pursuant to the terms and conditions of this Agreement and our Privacy Policy. Any action by you that, in our sole discretion: (i) violates the terms and conditions of this Agreement and/or the Privacy Policy; (ii) restricts, inhibits or prevents any access, use or enjoyment of our Services; or (iii) through the use of our Services, defames, abuses, harasses, offends or threatens others, shall not be permitted, and may result in your loss of the right to access and use our Services.</li>
              <li>The rights granted to you in these Terms are subject to the following restrictions: (i) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Services; (ii) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Services; (iii) you shall not access the Services in order to build a similar or competitive Service; and (iv) except as expressly stated herein, no part of the Services may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Any future release, update, or other addition to functionality of the Services shall be subject to these Terms.</li>
              <li>Furthermore, you agree that you will not use any robot, spider, scraper, deep link or other similar automated data gathering or extraction tools, program, algorithm or methodology to access, acquire, copy or monitor our Services or any portion of our Services or for any other purpose, without our prior written permission. Additionally, you agree that you will not: (i) take any action that imposes, or may impose in our sole discretion an unreasonable or disproportionately large load on our infrastructure; (ii) copy, reproduce, modify, create derivative works from, distribute or publicly display any content (except for your personal information) from our Services without our prior written permission and the appropriate third party, as applicable; (iii) interfere or attempt to interfere with the proper working of our Services or any activities conducted on our Services; (iv) bypass any robot exclusion headers or other measures we may use to prevent or restrict access to our Services, or (v) interfere or disrupt the Service or servers or networks connected to the Service, including by transmitting any worms, viruses, spyware, malware or any other code of a destructive or disruptive nature.</li>
              <li>Except as expressly permitted in this Agreement, you shall not collect or harvest any personally identifiable information, including account names, from our Services.</li>
              <li>Our Services may now, or in the future, have "publicly accessible areas" that allow users to post their own User Content that will be accessible by the public or the user population generally. As a user of the Services, you acknowledge and affirmatively agree that in the course of using the Services you may be exposed to User Content that might be offensive, harmful, inaccurate or otherwise inappropriate. You further agree that PlayerHub shall not, under any circumstances, be liable in any way for any User Content.</li>
              <li>You understand and agree that you are solely responsible for compliance with any and all laws, rules, regulations, and Tax obligations that may apply to your purchases or use of the Services.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Suspension and Termination of Services</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>PlayerHub may limit, suspend or terminate the Services to you if you fail to comply with these Terms, the Privacy Policy, the EULA for the App software or if you use the Services in a way that causes legal liability to us or disrupts use of the Service by other users.</li>
              <li>PlayerHub may also suspend the Services to you if we are investigating suspected misconduct by you. PlayerHub will use commercially reasonable efforts to narrow the scope and duration of any limitation or suspension under this Section as is needed to resolve the issue that prompted such action.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Information Accuracy</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>We attempt to ensure that information on our Website, in our App and in our Service is complete, accurate and current. Despite our best efforts, this information may occasionally be inaccurate, incomplete or out of date. We make no representation as to the completeness, accuracy, or currency of any information our Website, in our App and in our Service.</li>
              <li>Furthermore, information on our Website, in our App and in our Service may contain typographical errors or omissions. We reserve the right to correct or make changes in such information without notice to you.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Proprietary Rights</h2>
            <p className="mb-6">As between PlayerHub and you, PlayerHub, or its licensors, own and reserve all right, title and interest in, and to, the Service and all hardware, software and other items used to provide the Service, other than the rights explicitly granted to you to use the Service in accordance with these Terms. No title to, or ownership of, any proprietary rights related to the Service or software is transferred to you pursuant to these Terms. All rights not explicitly granted to you are reserved by PlayerHub.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Intellectual Property Rights</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Our names, graphics, avatars, videos, logos, page headers, button icons, scripts, and service names are our trademarks or trade dress in the United States and/or other countries (collectively the "Proprietary Marks"), and are owned by PlayerHub or licensed to us. You may not use the Proprietary Marks without our prior written permission.</li>
              <li>We make no proprietary claim to any third-party names, trademarks or service marks appearing on our Services including, without limitation, those owned by any participating merchants accessible via our Website. Any third-party names, copyrights, trademarks and service marks are property of their respective owners and users may not use them without independently obtaining a right to do so from the owner.</li>
              <li>The information, content, documentation, guides, descriptions, advice, data, software and any other content viewable on, contained in, or downloadable from our Services (collectively, "Our Content"), including, without limitation, all text, graphics, charts, pictures, photographs, images, videos, audio files, line art, icons and renditions, are copyrighted by PlayerHub, or otherwise licensed to us by Our Content suppliers.</li>
              <li>We also own a copyright of a collective work in the selection, coordination, arrangement, presentation, display and enhancement of Our Content (the "Collective Work").</li>
              <li>All software used on, or within our Website, App or Services is our property, or the property of our software vendors, and is protected by United States and international copyright laws. Viewing, reading, printing, listening to, downloading or otherwise using Our Content and/or the Collective Work does not entitle you to any ownership or intellectual property rights to Our Content, the Collective Work, or the Software.</li>
              <li>You are solely responsible for any damages resulting from your infringement of our, or any third-parties, intellectual property rights regarding the Trademarks, Our Content, the Collective Work, the Software and/or any other harm incurred by us or our affiliates as a, direct or indirect, result of your copying, distributing, redistributing, transmitting, publishing or using the same for purposes that are contrary to the terms and conditions of this Agreement.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Use of Our Content</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>We grant you a limited, revocable, non-sub licensable, non-exclusive, license to access, print, download or otherwise make personal use of Our Content and the Collective Work for your noncommercial personal use provided, however, that you shall not delete any proprietary notices or materials with regard to the foregoing.</li>
              <li>You may not modify Our Content or the Collective Work or utilize them for any commercial purpose or any other public display, performance, sale, or rental, decompile, reverse engineer, or disassemble Our Content and the Collective Work, or transfer Our Content or the Collective Work to another person or entity.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">User Content Rights and Related Responsibilities; Your License to PlayerHub</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>"User Content" means, without limitation, any images, photos, audio, video, artwork, text, messages, documents, digital files, music, hyperlinks, comments, reviews, feedback, suggestions, or any other content you upload, transmit or otherwise make available to PlayerHub, and/or its users, via the Services. You represent and warrant that you own or otherwise control the rights to your User Content and that each and every part thereof, is an original work by you, or you have obtained all rights, licenses, consents and permissions necessary in order to use those parts at any and all times. You further agree to indemnify PlayerHub and its affiliates for all claims arising from or in connection with any claims to any rights in your User Content, or any damages arising from our use of your User Content.</li>
              <li>By submitting User Content on or through the Service, you grant to PlayerHub, and to each of the PlayerHub users with whom you share your User Content, a perpetual, worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, re-use, broadcast, stream, download, reproduce, transmit, print, publish, display, exhibit, distribute, re-distribute, copy, host, store, cache, archive, index, categorize, edit, alter, modify, adapt, translate, create derivative works based upon, and to publicly perform such User Content without attribution, and without the requirement of any permission from, or payment to, you or to any other person or entity, in any manner including, without limitation, for commercial, publicity, trade, promotional, or advertising purposes, and in any and all media now known or hereafter devised. You retain all rights in your Content, subject to the rights you granted to us, and to our users, in these Terms.</li>
              <li>In order for us to provide the Service to you, we require that you grant us certain rights with respect to User Content, including the ability to share, transmit, perform, manipulate, process, store and copy User Content. Your acceptance of this Agreement gives us the permission to do so and grants us any such rights necessary to provide the Service to you.</li>
              <li>You agree that any User Content you submit to our Service in a public area of our Services may be viewed or heard by other users, any person visiting or participating in the Service, and by the public in general.</li>
              <li>PlayerHub expressly disclaims any liability for the loss or damage to any User Content or any losses or damages you incur as a result of the loss or damage of any User Content. It is your responsibility to back-up any User Content to prevent its loss.</li>
              <li>You are solely responsible for your User Content, including, without limitation, reviews, comments and feedback, and any damages suffered by PlayerHub resulting there from.</li>
              <li>PlayerHub may block, remove or return any User Content at any time in our sole discretion for any reason whatsoever, or for no reason at all. We are not responsible for the authenticity, accuracy, completeness, appropriateness, or legality of User Content.</li>
              <li>User Content is not considered to be confidential. You agree not to submit User Content to a public area of our Services, or to other users of our Services, in which you have any expectation of privacy or confidentiality.</li>
              <li>You may submit comments or ideas about the Services ("Ideas"). By submitting any Ideas, you agree that your disclosure is gratuitous, unsolicited, and without restriction, and that we are free to use, and disclose, the Ideas on a non-confidential basis or otherwise to anyone without any additional compensation to you.</li>
              <li>You agree not to upload or post to a publicly accessible part of Service any content that is knowingly false, offensive, inaccurate, incomplete, abusive, obscene, profane, threatening, intimidating, harassing, defamatory, racially or ethnically offensive, invasive of privacy or publicity rights, inclusive of hate speech, violates the rights of any party, gives rise to liability, is politically oriented, contains corrupted data or any other harmful, disruptive, or destructive files or would constitute or encourage a criminal offense.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Code of Conduct</h2>
            <p className="mb-6">PlayerHub is committed to providing a safe and friendly platform for our users. To ensure the best possible experience for all users of our Services, we have established some basic guidelines and rules for participation. By using our Services, you agree that you have read and will follow the rules and guidelines set forth below.</p>

            <p className="mb-6">Please take a moment to acquaint yourself with these important rules and guidelines. In order to preserve a climate that encourages productive, civil and meaningful interaction, PlayerHub reserves the right to suspend or terminate a user's account for a violation of these rules.</p>

            <p className="mb-6">You agree not to use our Service including, without limitation any text, chat or messaging communication system we may provide to transmit, distribute or post any User Content as defined in our Terms of Use, that is offensive, inaccurate, incomplete, abusive, obscene, profane, threatening, intimidating, harassing, racially offensive, or illegal material. The following includes examples, without limitation, of the things you may not do:</p>

            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Impersonate any person or entity.</li>
              <li>Stalk, harass, defame, abuse, bully, threaten or otherwise violate the legal rights of others.</li>
              <li>Advocate for or harass or intimidate another person.</li>
              <li>Promote information that is false or misleading.</li>
              <li>Promote illegal activities or conduct that is defamatory, libelous or otherwise objectionable.</li>
              <li>Promote violence, racism, bigotry, hatred or physical harm of any kind against any group or individual.</li>
              <li>Transmit anything that exploits children or minors or that depicts cruelty to animals.</li>
              <li>Solicit personal information from anyone under the age of 18.</li>
              <li>Use the service in an illegal manner or to commit an illegal act.</li>
              <li>Transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware.</li>
              <li>Transmit any content that contains video, audio, or images of another person without his or her permission or that of their legal guardian.</li>
              <li>Promote material that exploits people in a sexual, pornographic or violent manner.</li>
              <li>Provide instructional information about illegal activities.</li>
              <li>Infringe upon someone else's trademark, copyright or other intellectual property or other rights.</li>
            </ul>

            <p className="mb-6">PlayerHub reserves the right to suspend or terminate any user account at any time for any reason, with or without warning and without liability to the user.</p>

            <p className="mb-6">If you violate these guidelines, we may remove the offending content, suspend or terminate your account, and notify law enforcement. Please respect and honor these guidelines and report any violations to help@playerhub.co to help us create a better community.</p>

            <p className="mb-6">We have no obligation to delete content that you find personally objectionable or offensive.</p>
            <p className="mb-6">We reserve the right to modify these rules with or without notice at any time.</p>

            <p className="mb-6">If you have questions, comments, concerns or feedback regarding these guidelines or our Services, please contact us at help@playerhub.co.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Interruption of Service</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Your access and use of our Services may be interrupted from time to time for any of several reasons, including, without limitation, inability to access a network to connect to the internet from your location, the malfunction of your or our equipment, periodic updating, maintenance or repair of our Services or other actions that we, in our sole discretion, may elect to take.</li>
              <li>You agree that we will not be liable to you or to any third party for any interruption of the Services or any part thereof.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Third Party Links and Affiliates; Products, Services and Content</h2>
            <p className="mb-6">Our Service may contain features, services and functionalities linking you to, or providing you with, access to third party products, merchandise, services, content, websites, directories, servers, networks, systems, information, databases, applications, software, programs, and the Internet as a whole. In certain instances, we may have an Affiliate relationship with these third parties and receive compensation from the operator of the third party website by virtue of your clicking to, or making a purchase on, that site. Because we have no control over such sites and resources, we are not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any products, merchandise, services, content, advertising or other materials on, or available from, such websites or resources. When you visit or use a third party's website you are thereafter subject to, agree to read and consent to the third party's Terms of Use and Privacy Policy and you release us from any liability.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">PlayerHub Mobile App Software End User License Agreement (EULA)</h2>
            <p className="mb-6">THE PLAYERHUB TERMS OF USE AND PRIVACY POLICY TERMS AND CONDITIONS, TO THE EXTENT NOT STATED HEREIN, ARE HEREBY INCORPORATED HEREIN AND MADE A PART HEREOF BY REFERENCE AS IF SET FORTH IN FULL.</p>

            <p className="mb-6">THIS EULA, TOGETHER WITH THE PLAYERHUB TERMS OF USE AND PRIVACY POLICY, ARE THE ENTIRE AND EXCLUSIVE AGREEMENT BETWEEN YOU AND PLAYERHUB WITH RESPECT TO THE USE OF THE APP AND OUR SERVICE.</p>

            <p className="mb-6">BY INSTALLING THE APP OR OTHERWISE ACCESSING OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS EULA, INCLUDING THE WARRANTY DISCLAIMERS, INDEMNITY, RELEASE, LIMITATION OF LIABILITY PROVISIONS AND OTHER TERMS CONTAINED IN THE PLAYERHUB TERMS OF USE AND PRIVACY POLICY. IF YOU DO NOT AGREE, THEN YOU MAY NOT USE THE SERVICE. IF YOU DO NOT UNDERSTAND OR AGREE TO THESE TERMS, DO NOT INSTALL THE APP OR OTHERWISE ACCESS OR USE OUR WEBSITE OR SERVICE.</p>

            <p className="mb-6">We make software available to users in order to access the PlayerHub mobile App via a mobile device ("Mobile Software"). To use the Mobile Software you must have a mobile device that is compatible with the Mobile Software. PlayerHub does not warrant that the Mobile Software will be compatible with your mobile device.</p>

            <p className="mb-6">PlayerHub hereby grants you a non-exclusive, non-transferable, revocable license to use a compiled code copy of the Mobile Software for one PlayerHub account on a mobile device owned or leased solely by you, for your personal use.</p>

            <p className="mb-6">You may not: (a) modify, disassemble, decompile or reverse engineer the Mobile Software; (b) rent, lease, loan, resell, sublicense, distribute or otherwise transfer the Mobile Software to any third party or use the Mobile Software to provide time sharing or similar services for any third party; (c) make any copies of the Mobile Software; (d) remove, circumvent, disable, damage or otherwise interfere with security-related features of the Mobile Software, features that prevent or restrict use or copying of any content accessible through the Mobile Software, or features that enforce limitations on use of the Mobile Software; or (e) delete the copyright, trademark and other proprietary rights notices on the Mobile Software.</p>

            <p className="mb-6">You agree that PlayerHub may collect and use data, including but not limited to technical information about your mobile device, computer and physical location to facilitate the provision of user support, technical support, product improvement and software updates.</p>

            <p className="mb-6">You acknowledge that PlayerHub may from time to time issue upgraded versions of the Mobile Software, and may automatically electronically upgrade the version of the Mobile Software that you are using on your mobile device. You consent to such automatic upgrading on your mobile device, and agree that the terms and conditions of this Agreement will apply to all such upgrades.</p>

            <p className="mb-6">Any third-party code that may be incorporated in the Mobile Software is covered by the applicable open source or third-party license EULA, if any, authorizing use of such code.</p>

            <p className="mb-6">The foregoing license grant is not a sale of the Mobile Software or any copy thereof, and PlayerHub or its third party partners or suppliers retain all right, title, and interest in the Mobile Software (and any copy thereof). Any attempt by you to transfer any of the rights, duties or obligations hereunder, except as expressly provided for in this Agreement, is void. PlayerHub reserves all rights not expressly granted under this Agreement.</p>

            <p className="mb-6">The Mobile Software originates in the United States, and is subject to United States export laws and regulations. You may not use or otherwise export or re-export the App except as authorized by United States law and the laws of the jurisdiction in which the App was obtained. In particular, but without limitation, the App may not be exported or re-exported (a) into any U.S. embargoed countries or (b) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person's List or Entity List. By using the App, you represent and warrant that (i) you are not located in any a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a terrorist-supporting country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also agree that you will not use these products for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture or production of nuclear missiles, or chemical or biological weapons.</p>

            <p className="mb-6">The Software and Documentation are provided with United States government Restricted Rights. Use, duplication, or disclosure by the United States government is subject to restrictions as set forth in subparagraph (c)(f)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (b) (1) and (2) of the Commercial Computer Software-Restricted Rights at 48 C.F.R. S:52.227-19, as applicable.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Mobile Application from a Third Party App Store</h2>
            <p className="mb-6">The following applies to any App Store Sourced Application accessed through or downloaded from a Third Party App Store:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>You acknowledge and agree that (i) the Terms are concluded between you and PlayerHub only, and not the Third Party App Store, and (ii) PlayerHub, not the Third Party App Store, is solely responsible for the App Store Sourced Application and content thereof. Your use of the App Store Sourced Application must comply with the Third Party App Store Terms of Use.</li>
              <li>You acknowledge that the Third Party App Store has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Application.</li>
              <li>In the event of any failure of the App Store Sourced Application to conform to any applicable warranty, you may notify the Third Party App Store, and the Third Party App Store will refund the purchase price for the App Store Sourced Application to you, and to the maximum extent permitted by applicable law, the Third Party App Store will have no other warranty obligation whatsoever with respect to the App Store Sourced Application. As between PlayerHub and the Third Party App Store, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of PlayerHub.</li>
              <li>You and PlayerHub acknowledge that, as between PlayerHub and the Third Party App Store, the Third Party App Store is not responsible for addressing any claims you have or any claims of any third party relating to the App Store Sourced Application or your possession and use of the App Store Sourced Application, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</li>
              <li>You and PlayerHub acknowledge that, in the event of any third-party claim that the App Store Sourced Application or your possession and use of that App Store Sourced Application infringes that third party's intellectual property rights, as between PlayerHub and the Third Party App Store, PlayerHub, not the Third Party App Store, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by the Terms.</li>
              <li>You and PlayerHub acknowledge and agree that the Third Party App Store, and their subsidiaries, are third-party beneficiaries of the Terms as related to your license of the App Store Sourced Application, and that, upon your acceptance of the terms and conditions of the Terms, the Third Party App Store will have the right (and will be deemed to have accepted the right) to enforce the Terms as related to your license of the App Store Sourced Application against you as a third-party beneficiary thereof.</li>
              <li>Without limiting our Terms of Use, you must comply with all applicable third-party terms of agreement when using the Third Party App Store Sourced Application.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Electronic Communications</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Although we may choose to communicate with you by regular mail, we may also choose to communicate with you by electronic means including, without limitation, email, telephone, text, SMS or by posting notices on our Services. When you use our Services, you consent to communicating with us electronically.</li>
              <li>You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Third Party Social Networking</h2>
            <p className="mb-6">PlayerHub may now, or in the future, support sign-on from third-party social networking sites to make it easier for you to sign in or create an account with PlayerHub. If you elect to sign-on through a third-party social networking site, you may use those credentials, which will automatically be linked to your account. Use of third-party platforms to create and access your account is subject to the terms and conditions and privacy policies of such third parties. If you access our Services through a third party social networking site or application including, but not limited to, Facebook, Instagram, LinkedIn or X (formerly Twitter), you agree that you have read the third party social networking site Terms of Service and Privacy Policy, authorize PlayerHub to access and store certain information about you that is made available through that third party social networking site, and further authorize us to collect, store, retain and use, your information in accordance with our Privacy Policy.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Security</h2>
            <p className="mb-6">Violating the security of our Services is prohibited and may result in criminal and civil liability. PlayerHub may investigate incidents involving such violations and may involve, and will cooperate with law enforcement if a criminal violation is suspected. Security violations include, without limitation, unauthorized access to, or use of, data or systems including any attempt to probe, scan, or test the vulnerability of the Service or to breach security or authentication measures, unauthorized monitoring of data or traffic and interference with service to any user, host, or network.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Privacy and Your Personal Information</h2>
            <p className="mb-6">For information about the PlayerHub data protection practices and privacy policies, please read our Privacy Policy here (include link to Privacy Policy page here). This policy explains how we treat your personal information, and protect your privacy when you use the Services. You agree to the use of your data in accordance with PlayerHub Privacy Policy.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Copyright and Intellectual Property Policy</h2>
            <p className="mb-6">We respect the intellectual property rights of others. We reserve the right to remove any User Content on the Services which allegedly infringe upon another person's copyright, trademark or other intellectual property right, and/or terminate, discontinue, suspend and/or restrict the account or ability to visit and/or use the Services or remove, edit, or disable any User Content on the Services which allegedly infringe upon another person's intellectual property rights. We provide this policy pursuant to Section 512 of the Copyright Revision Act, as enacted through the Digital Millennium Copyright Act ("DMCA").</p>

            <p className="mb-6">A valid complaint under the DMCA must provide the following information in writing:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>An electronic or physical signature of a person authorized to act on behalf of the copyright owner.</li>
              <li>Identification of the copyrighted work that you claim has been infringed.</li>
              <li>Identification of the material that is claimed to be infringing and where it is located on the Service.</li>
              <li>Information reasonably sufficient to permit us to contact you, such as your address, telephone number, and, email address.</li>
              <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law.</li>
              <li>A statement, made under penalty of perjury, that the above information is accurate, and that you are the copyright owner or are authorized to act on behalf of the owner.</li>
            </ul>

            <p className="mb-6">Federal law provides that if you knowingly misrepresent that online material is infringing, you may be subject to criminal prosecution for perjury and civil penalties, including monetary damages, court costs, and attorneys' fees. The above information must be submitted to the Copyright Agent at: help@playerhub.co</p>

            <h3 className="text-lg font-semibold mt-6 mb-4">Counter-Notice</h3>
            <p className="mb-6">If you receive notification that your User Content has been removed from the Services, you have an opportunity to appeal this removal if you believe that your User Content was removed in error. If you believe that the removed User Content does not violate any third-party rights, or you have authorization from the rights-holder or the rights-holder's authorized agent to use the material in question, you may appeal the removal by sending an email notice to the Copyright Agent at: help@playerhub.co with the following information:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Your physical or electronic signature.</li>
              <li>Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled.</li>
              <li>A statement under penalty of perjury that you have a good-faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled.</li>
              <li>Your name, address, and telephone number, and a signed statement that you consent to the jurisdiction of state and federal courts in the state of Illinois, and that you will accept service of process from the party who made the initial infringement claim (or their authorized agent) if they choose to pursue legal action.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Disclaimers; No Warranties</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>YOU EXPRESSLY AGREE THAT YOUR USE OF THE PLAYERHUB SERVICE IS AT YOUR SOLE RISK, AND YOU ASSUME ALL RISK. ALL SOFTWARE, SERVICES AND PRODUCTS AVAILABLE FROM PLAYERHUB ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, PLAYERHUB AND ITS PARENTS, SUBSIDIARIES, PARTNERS, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES AND AGENTS, (COLLECTIVELY, THE "PLAYERHUB PARTIES") DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</li>
              <li>PLAYERHUB DOES NOT REPRESENT OR WARRANT THAT THE INFORMATION ACCESSIBLE THROUGH OUR SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR-FREE. THE RELIANCE ON ANY INFORMATION PROVIDED THROUGH THE SERVICE IS SOLELY AT YOUR OWN RISK.</li>
              <li>WITHOUT LIMITING THE FOREGOING, WE MAKE NO WARRANTY THAT (I) THE SERVICES OR PRODUCTS WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, OR (III) THE QUALITY OF ANY SERVICES, INFORMATION OR PRODUCTS OBTAINED BY YOU FROM OR THOUGH US WILL MEET YOUR EXPECTATIONS.</li>
              <li>THE SERVICES CAN INCLUDE TECHNICAL OR OTHER FAULTS, INACCURACIES OR TYPOGRAPHICAL ERRORS. FURTHERMORE, THE INFORMATION OR SERVICES ON THIS SITE OR APP MAY BE OUT OF DATE. WE MAY MAKE CHANGES TO THE SERVICES, INFORMATION OR PRODUCTS ON THIS SITE OR APP, INCLUDING THE DESCRIPTIONS AND PRICES OF ANY PROMOTIONAL OFFERS, SERVICES OR OTHER PRODUCTS LISTED HEREIN AT ANY TIME WITHOUT NOTICE, HOWEVER WE HAVE NO OBLIGATION TO DO SO.</li>
              <li>THE PLAYERHUB PARTIES DO NOT WARRANT THAT THE SERVICES OR THE SERVERS THAT MAKE THE SERVICE AVAILABLE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT ANY PRODUCT DESCRIPTION OR OTHER CONTENT OFFERED AS PART OF THE SERVICES, ARE ACCURATE, RELIABLE, CURRENT OR COMPLETE.</li>
              <li>YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. IF YOU DOWNLOAD ANY CONTENT FROM THE SERVICE, YOU DO SO AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PHONE, DIGITAL DEVICE OR COMPUTER, OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT THROUGH THE SERVICE.</li>
              <li>WE RESERVE THE RIGHT TO RESTRICT OR TERMINATE YOUR ACCESS TO THE SERVICE OR ANY FEATURE OR PART THEREOF AT ANY TIME.</li>
              <li>SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME PARTS OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Limitation of Liability</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>YOUR USE OF THE PLAYERHUB SERVICE IS AT YOUR SOLE RISK AND IN NO EVENT SHALL WE BE RESPONSIBLE TO, OR LIABLE TO YOU, OR ANY THIRD PARTY, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, FOR ANY DAMAGES INCLUDING, BUT NOT LIMITED TO, SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES THAT INCLUDE, BUT ARE NOT LIMITED TO, DAMAGES FOR ANY PERSONAL INJURY TO YOU OR OTHERS, OR LOSS OF PROFIT, REVENUE OR BUSINESS, AS A DIRECT OR INDIRECT RESULT OF: (I) YOUR ACCESS AND USE OF OUR SERVICES AND PRODUCTS; (II) YOUR BREACH OR VIOLATION OF THE TERMS AND CONDITIONS OF THIS AGREEMENT; (III) YOUR DELAY IN ACCESSING OR INABILITY TO ACCESS OR USE OUR SERVICES FOR ANY REASON; (IV) YOUR DOWNLOADING OF ANY OF OUR CONTENT OR THE COLLECTIVE WORK FOR YOUR USE; OR (V) YOUR RELIANCE UPON OR USE OF OUR CONTENT OR THE COLLECTIVE WORK, WHETHER RESULTING IN WHOLE OR IN PART, FROM BREACH OF CONTRACT, TORTIOUS BEHAVIOR, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF WE AND/OR OUR SUPPLIERS HAD BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.</li>
              <li>THIS LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS, INCLUDING PROMOTIONAL OFFERS, PURCHASED IN, RECEIVED THROUGH OR ADVERTISED IN OUR SERVICES, OR RECEIVED THROUGH ANY LINKS PROVIDED IN OUR SERVICES.</li>
              <li>WITHOUT LIMITING THE FOREGOING, UNDER NO CIRCUMSTANCES SHALL WE BE HELD LIABLE FOR ANY DELAY OR FAILURE IN PERFORMANCE RESULTING DIRECTLY OR INDIRECTLY FROM ACTS OF NATURE, FORCES, OR CAUSES BEYOND OUR REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, INTERNET FAILURES, COMPUTER EQUIPMENT FAILURES, TELECOMMUNICATION EQUIPMENT FAILURES, OTHER EQUIPMENT FAILURES, ELECTRICAL POWER FAILURES, STRIKES, LABOR DISPUTES, RIOTS, INSURRECTIONS, CIVIL DISTURBANCES, SHORTAGES OF LABOR OR MATERIALS, FIRES, FLOODS, STORMS, EXPLOSIONS, ACTS OF GOD, WAR, GOVERNMENTAL ACTIONS, ORDERS OF DOMESTIC OR FOREIGN COURTS OR TRIBUNALS OR NON-PERFORMANCE OF THIRD PARTIES.</li>
              <li>OUR LIABILITY AND THE LIABILITY OF OUR AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES, INDEPENDENT CONTRACTORS, SHAREHOLDERS, REPRESENTATIVES, AND AGENTS ARISING OUT OF THIS AGREEMENT SHALL NOT EXCEED THE LESSER OF EITHER THE AMOUNTS ACTUALLY PAID BY USER IN THE PURCHASE OR TRANSACTION GIVING RISE TO SUCH CLAIM OR $50.</li>
              <li>YOU AND WE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO OUR SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</li>
              <li>CERTAIN STATE OR JURISDICTIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Indemnity</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>You agree that you will be personally responsible for your use of the Service and you further agree to defend, indemnify and hold harmless PlayerHub and its officers, directors, employees, consultants, affiliates, subsidiaries and agents from and against any and all claims, liabilities, damages, losses and expenses, including reasonable attorneys' and accounting fees and costs, arising out of or in any way connected with (i) your access to, use of, or alleged use of the Service; (ii) your violation of these Terms of Use or any representation, warranty, or agreements referenced herein, or any applicable law or regulation; (iii) your infringement upon the property rights, intellectual property rights (copyrights and trademarks) or other rights of others; (iv) your violation of any third party right, including without limitation publicity, confidentiality, or privacy right; (v) any death, or serious physical or serious emotional harm, to you or any third party resulting from your use of the Services.</li>
              <li>We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with our defense of such claim.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Release</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>IN EXCHANGE FOR YOUR RIGHT TO USE THE SERVICES, YOU RELEASE, TO THE MAXIMUM EXTENT ALLOWED BY LAW, PLAYERHUB, ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, AND AGENTS FROM CLAIMS, DEMANDS AND DAMAGES OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED, INCLUDING, WITHOUT LIMITATION, ANY DEATH OR SERIOUS EMOTIONAL OR SERIOUS PHYSICAL HARM, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, YOUR USE OF OUR WEBSITE, APPS AND SERVICES, AND ANY PRODUCTS OR MERCHANDISE RECEIVED OR PURCHASED THROUGH THE USE OF OUR SERVICE.</li>
              <li>IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE §1542, WHICH SAYS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR."</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Governing Law</h2>
            <p className="mb-6">This Agreement, and any separate agreements whereby we provide you Services, shall be governed by and construed in accordance with the laws of the State of Illinois, without regard to its conflicts of laws principles. The parties hereby consent to the exclusive jurisdiction and venue in the state and federal courts in the State of Illinois in and for the County in which PlayerHub has established its principal office.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Our Remedies</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>You acknowledge that we may be irreparably damaged if this Agreement is not specifically enforced, and damages at law would be an inadequate remedy. Therefore, in the event of a breach or threatened breach of any provision of this Agreement by you, we shall be entitled, in addition to all rights and remedies, to an injunction restraining such breach or threatened breach, without being required to show any actual damage or to post an injunction bond, and/or to a decree for specific performance of the provisions of this Agreement.</li>
              <li>For purposes of this Section, you agree that any action or proceeding with regard to such injunction restraining such breach or threatened breach shall be brought in the state courts of record or a United States District Court for the State of Illinois in and for the County in which PlayerHub has established its principal office. You consent to the jurisdiction of such court and waive any objection to the venue of any such action or proceeding in such court.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Dispute Resolution</h2>
            <p className="mb-6">PLEASE READ THIS SECTION CAREFULLY. THIS SECTION CONTAINS AN AGREEMENT TO ARBITRATE, WHICH WILL, WITH LIMITED EXCEPTION, REQUIRE YOU TO SUBMIT CLAIMS YOU HAVE AGAINST US TO BINDING AND FINAL ARBITRATION. THIS SECTION ALSO CONTAINS AN AGREEMENT THAT YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING.</p>

            <p className="mb-6">You and PlayerHub agree that any claim or dispute at law or equity that has arisen, or may arise, between you and PlayerHub (including any claim or dispute between you and a third-party agent of PlayerHub) that relates in any way to or arises out of this or previous versions of this Agreement, your use of or access to the Services, the actions of PlayerHub or its agents, or any products or services sold or purchased through the Services, will be resolved in accordance with the provisions set forth in this Dispute Resolution Section.</p>

            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Applicable Law. You agree that, except to the extent inconsistent with or preempted by federal law, the laws of the State of Illinois, without regard to principles of conflict of laws, will govern this Agreement and any claim or dispute that has arisen or may arise between you and PlayerHub, except as otherwise stated in this Agreement.</li>
              <li>Agreement to Arbitrate. This Dispute Resolution by Binding Arbitration section is referred to in these Terms as the "Arbitration Agreement." You agree that any and all disputes or claims that have arisen or may arise between you and PlayerHub, whether arising out of or relating to these Terms of Service (including any alleged breach thereof), the Services, any advertising, any aspect of the relationship or transactions between us, shall be resolved exclusively through final and binding arbitration, rather than a court, in accordance with the terms of this Arbitration Agreement, except that you may assert individual claims in small claims court, if your claims qualify. You agree that, by entering into these Terms, you and PlayerHub are each waiving the right to a trial by jury or to participate in a class action. Your rights will be determined by a neutral arbitrator, not a judge or jury. If you reside in the U.S., the Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.</li>
              <li>PROHIBITION OF CLASS AND REPRESENTATIVE ACTIONS AND NON-INDIVIDUALIZED RELIEF. YOU AND PLAYERHUB AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH YOU AND PLAYERHUB AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON'S OR PARTY'S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY'S INDIVIDUAL CLAIM(S).</li>
              <li>Pre-Arbitration Dispute Resolution. We at PlayerHub believe that most customer concerns can be resolved quickly and to the customer's satisfaction by emailing customer support at help@playerhub.co. If such efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute ("Notice"). The Notice to PlayerHub should be sent to the address provided in the Contact Us section at the end of these Terms of Service ("Notice Address"). The Notice must (i) describe the nature and basis of the claim or dispute and (ii) set forth the specific relief sought. If PlayerHub and you do not resolve the claim within sixty (60) calendar days after the Notice is received, you or PlayerHub may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by PlayerHub or you shall not be disclosed to the arbitrator during the arbitration proceeding.</li>
              <li>Arbitration Procedures. Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Association's ("AAA") rules and procedures, including the AAA's Supplementary Procedures for Consumer-Related Disputes (collectively, the "AAA Rules"), as modified by this Arbitration Agreement. For information on the AAA, please visit its website, http://www.adr.org. If there is any inconsistency between any term of the AAA Rules and any term of this Arbitration Agreement, the applicable terms of this Arbitration Agreement will control unless the arbitrator determines that the application of the inconsistent Arbitration Agreement terms would not result in a fundamentally fair arbitration. The arbitrator must also follow the provisions of these Terms of Service as a court would. All issues are for the arbitrator to decide, including, but not limited to, issues relating to the scope and enforceability of this Arbitration Agreement. Although arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings, the arbitrator can award the same damages and relief on an individual basis that a court can award to an individual under the Terms of Service and applicable law. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons. Unless PlayerHub and you agree otherwise, any arbitration hearings will take place in a reasonably convenient location for both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, the determination shall be made by AAA. If your claim is for USD $10,000 or less, PlayerHub agrees that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules. If your claim exceeds USD $10,000, the right to a hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based.Payment of all filing, administration, and arbitrator fees (collectively, the "Arbitration Fees") will be governed by the AAA Rules, unless otherwise provided in this Arbitration Agreement. Any payment of attorneys' fees will be governed by the AAA Rules.</li>
              <li>Confidentiality. All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties.</li>
              <li>Severability. If a court or the arbitrator decides that any term or provision of this Arbitration Agreement (other than the subsection titled "Prohibition of Class and Representative Actions and Non-Individualized Relief" above) is invalid or unenforceable, the parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement shall be enforceable as so modified. If a court or the arbitrator decides that any of the provisions of the subsection above titled "Prohibition of Class and Representative Actions and Non-Individualized Relief" are invalid or unenforceable, then the entirety of this Arbitration Agreement shall be null and void. The remainder of the Terms of Service will continue to apply.</li>
              <li>Judicial Forum for Legal Disputes. Unless you and we agree otherwise, in the event that the Arbitration Agreement above is found not to apply to you or to a particular claim or dispute as a result of a decision by the arbitrator or a court order, you agree that any claim or dispute that has arisen or may arise between you and us must be resolved exclusively by a state or federal court located in the State of Illinois in and for the County in which PlayerHub has established its principal office. You and we agree to submit to the personal jurisdiction of the courts located within the State of Illinois for the purpose of litigating all such claims or disputes. You also agree that: (i) our Services shall be deemed solely based in the State of Illinois; and (ii) our Services shall be deemed passive Services that do not give rise to personal jurisdiction over us and our assigns, either specific or general, in jurisdictions other than the State of Illinois.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Law Enforcement</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>PlayerHub is committed to cooperating with law enforcement while respecting each individual's right to privacy. If PlayerHub receives a request for user account information from a government agency investigating criminal activity, we will review the request to be certain that it satisfies all legal requirements before releasing information to the requesting agency.</li>
              <li>Furthermore, under 18 U.S.C. §§ 2702(b)(8) and 2702(c)(4) (Voluntary Disclosure Of Customer Communications or Records), PlayerHub may disclose user account information to law enforcement, without a subpoena, court order, or search warrant, in response to a valid emergency when we believe that doing so is necessary to prevent death or serious physical harm to someone. PlayerHub will not release more information than it prudently believes is necessary to prevent harm in an emergency situation.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-4">Statutory Rights; Notice To California Residents</h2>
            <p className="mb-6">If you are a California resident, under California Civil Code Section 1789.3, you may contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing, currently at: 1625 N. Market Blvd., Suite N-112, Sacramento, California 95834, or by telephone, currently at (800) 952-5210 in order to resolve a complaint regarding our Website.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Amendments to this Agreement</h2>
            <p className="mb-6">We reserve the right to update, amend and/or change this Agreement at any time in our sole discretion and without notice. Updates to this Agreement will be posted here. Amendments will take effect immediately upon us posting the updated Agreement on our Services. You are encouraged to revisit this Agreement from time to time in order to review any changes that have been made. The date on which this Agreement was last updated will be noted immediately below this Agreement. Your continued access and use of our Services following the posting of any such changes shall automatically be deemed your acceptance of all changes.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Severability</h2>
            <p className="mb-6">If any portion of this Agreement is deemed unlawful, void or unenforceable by any arbitrator or court of competent jurisdiction, this Agreement as a whole shall not be deemed unlawful, void or unenforceable, but only that portion of this Agreement that is unlawful, void or unenforceable shall be stricken from this Agreement.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">No Waiver</h2>
            <p className="mb-6">Our failure to enforce any right or provision in these Terms shall not constitute a waiver of such right or provision unless acknowledged and agreed to by us in writing.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Term and Termination</h2>
            <p className="mb-6">This Agreement is effective beginning when you a) first accept the Terms by clicking "accept" or "agree" to this Agreement or you first access or use our Services; or b) register and purchase a Subscription Plan. This Agreement will terminate upon your request to cancel your registered PlayerHub account, or request to cancel your Subscription Plan. PlayerHub may, at its sole discretion, terminate this Agreement, or suspend or terminate your access to our Services, at any time for any reason or no reason, with or without notice. Upon termination of this Agreement, by you or PlayerHub, your license rights will terminate and you must immediately cease all use of Website, App and Services.</p>

            <h2 className="text-xl font-semibold mt-8 mb-4">Entire Understanding</h2>
            <p className="mb-6">This Agreement and the Privacy Policy represent the entire understanding and agreement between you and us regarding the subject matter of the same, and supersede all other previous agreements, understandings and/or representations regarding the same.</p>

            <div className="mt-8 border-t pt-8">
              <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
              <p>If you have to provide us with any Notice, or have any questions, comments, concerns or feedback regarding this Agreement or our Services, please contact us at help@playerhub.co or mail us here:</p>
              <p className="mt-4">
                Player Hub, Inc.<br />
                ______________________________<br />
                ______________________________
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer activePage="terms" />
    </div>
  );
};

export default Terms;